a = "abcdef" < "xxx"
print a, "\n"
a = "abcdef" > "xxx"
print a, "\n"
a = "abcdef" <= "xxx"
print a, "\n"
a = "abcdef" >= "xxx"
print a, "\n"
a = 3
print a, "\n"
a = "abcdef \n" != "xxx"
print a, "\n"