a = "abcdef" < "xxx"
print a, "\n"
a = "abcdef" > "xxx"
print a, "\n"
a = "abcdef" <= "xxx"
print a, "\n"
a = "abcdef" >= "xxx"
print a, "\n"
a = "abcdef" == "xxx"
print a, "\n"
a = "abcdef" != "xxx"
print a, "\n"